[#180][DOC] Issue 템플릿 등 가독성 확보 및 Label 이모지 정상화
knowease-inc/knowease-inc.github.io pull request #181
Opened 2024-08-27 22:34 UTC by tooget

## 이 PR로 아래의 이슈가 해결될 수 있습니다
> 이 PR이 성공적으로 merge될 경우 **자동적으로 클로즈할** 이슈 번호를 **1개 이상** 적어주세요.
 - resolved: #180

## 이 PR이 머지될 경우 혹시나 이런 문제가 있을 수도 있습니다
> **혹시나 예상되는** 서비스 운영 관점의 문제점과, 문제발생시 대응방법을 **1개 이상** 적어주세요.
 - [ ] 개발환경에 영향을 주어 어플리케이션이 정상작동하지 않을 가능성, 롤 백

2024-08-29 02:32 UTC, T-Mook commented
@tpdud406 

- 여기 포함해서 리뷰 요청되어 있는 곳들 한 번씩 확인하시고 리뷰 완료 해주세요~

2024-08-30 03:07 UTC, tpdud406 requested changes

2024-08-30 04:03 UTC, tooget commented on README.md
>  > ref: https://ko.nuxtjs.org/docs/2.x/deployment/github-pages/
@tpdud406 

> 현재 링크가 nuxt2 버전인 것 같아 눌러보니 페이지가 나오지 않습니다. (Page Not Found)

 - 확인 감사합니다. 역시 👍  -> https://github.com/knowease-inc/knowease-inc.github.io/pull/181/commits/9e30229cf3d5f62ec766b35ce2d996bcaf2158c9 링크 수정하였습니다!

> 혹시 필요한 사항이라면 nuxt3 배포([링크](https://nuxt.com/deploy/github-pages))로 변경해야 할 것 같습니다.

 - 회사 홈페이지 Nuxtjs 버전은 현재 2.x 로 빌드되고 있습니다. (우선순위 고려) 현행 유지 혹은 3.x 로 업그레이드 혹은 다른 프런트엔드 프레임워크 (Nextjs?) 등 테스트베드로 이용 등 여러 선택지와 있을 것 같습니다. 어떤 방향이 좋을 것 같으신가요? @tpdud406 
https://github.com/knowease-inc/knowease-inc.github.io/blob/d168a87d5185e79974a1970029982c94c2a5d2d0/package.json#L20-L28

2024-08-30 04:05 UTC, T-Mook commented on README.md
>  > ref: https://ko.nuxtjs.org/docs/2.x/deployment/github-pages/
> 회사 홈페이지 Nuxtjs 버전은 현재 2.x 로 빌드되고 있습니다. (우선순위 고려) 현행 유지 혹은 3.x 로 업그레이드 혹은 다른 프런트엔드 프레임워크 (Nextjs?) 등 테스트베드로 이용 등 여러 선택지가 있을 것 같습니다. 어떤 방향이 좋을 것 같으신가요? @tpdud406

@tooget @tpdud406 

- 회사 홈페이지는 현행 유지로 해주시면 감사하겠습니다~

2024-08-30 04:08 UTC, tooget commented on README.md
>  > ref: https://ko.nuxtjs.org/docs/2.x/deployment/github-pages/
@tpdud406
 - 링크 자체는 Nuxtjs 2.x 로 정정했으니 이 conversation은 Resolve하겠습니다~

2024-08-30 04:56 UTC, T-Mook commented
@tpdud406 

- 추가 문제가 없다면, 리뷰 승인해주시면 됩니다~

2024-08-30 05:47 UTC, tpdud406 approved these changes

2024-08-30 05:47 UTC, tpdud406 commented
@tpdud406 
- 확인했습니다~~!

2024-08-30 05:51 UTC, merged