[#188][FEATURE] 고객사 컴포넌트 (고객사 CI) 추가 및 서브 서비스 표기
knowease-inc/knowease-inc.github.io pull request #189
Opened 2024-09-30 00:05 UTC by tpdud406

## 이 PR로 아래의 이슈가 해결될 수 있습니다
> 이 PR이 성공적으로 merge될 경우 **자동적으로 클로즈할** 이슈 번호를 "#"을 붙여서 **1개 이상** 적어주세요.

 - resolved: #188

## 아래의 내용과 같이 개발상 정상적으로 동작함을 확인하였습니다.
> 개발시 정상적으로 동작하였음을 확인할 수 있는 스크린샷, 동작 로그 등을 **1개 이상** 적어주세요.

 - TBD

## 이 PR이 머지될 경우, 혹시나 이런 문제가 있을 수도 있습니다
> **혹시나 예상되는** 서비스 운영상 **1개 이상** 적어주세요.

 - TBD

## 이 PR이 머지된 후 예상되는 문제가 실제로 발생하면 이러한 대응이 필요합니다.
> 실제 문제가 발생할 경우, 서비스 운영을 정상화시킬 수 있는 방법을 적어주세요.

 - TBD

2024-09-30 02:04 UTC, T-Mook requested changes
@tpdud406 

- https://github.com/knowease-inc/knowease-inc.github.io/issues/188#issuecomment-2378789603
- 위 내용 반영 안 된것 같은데 확인 부탁드려요~

#### 추가
1. 교육 서비스 문구 수정
   - 전: AI, DX(Digital Transformation) 교육 직접 제공
   - 후: 알기 쉬운 AI, 디지털 전환(DX, Digital Transformation), 비개발자 프로그래밍 온·오프라인 교육, 세미나, 컨설팅 제공

2024-09-30 02:21 UTC, T-Mook requested changes
- 데스크톱 사이즈에서 아래도 삭제 부탁드립니다~
![스크린샷 2024-09-30 오전 11 21 09](https://github.com/user-attachments/assets/e3fad303-6df6-4454-b6fd-73c52b1ce2c0)
- 이거 삭제하고나면 살짝 허전해질테니 CI 개수를 반으로 나눠서 2행으로 만들어주는게 나을 것 같습니다.

2024-09-30 11:10 UTC, tpdud406 commented
@T-Mook 

- 코멘트를 늦게 봤습니다.. 말씀하신 사항은 반영했습니다. (타이틀 일부 제거, CI 2행 출력)
- 가운데 정렬 괜찮을까요~?

<img width="250" alt="스크린샷 2024-09-30 오후 8 08 45" src="https://github.com/user-attachments/assets/e39d4ead-3a90-4946-854f-341d332c6d37">
<img width="508" alt="스크린샷 2024-09-30 오후 8 06 21" src="https://github.com/user-attachments/assets/4e7a1751-3096-4612-bd1e-5e43cccf95ed">

2024-09-30 13:25 UTC, T-Mook approved these changes

2024-09-30 15:15 UTC, merged

2024-10-01 00:04 UTC, T-Mook commented
@tpdud406 

- 현재 배포된 코드에 데스크톱 아래처럼 나오네요. 모바일도 확인 후 수정 부탁드립니다. **이슈 하나 새로 열어서요~**
- 모바일에서는 CI가 2줄로 나오지 않아도 되니, 원래대로 자연스럽게 나오도록 해주세요

![화면 캡처 2024-10-01 090209](https://github.com/user-attachments/assets/d98dd143-bbbf-49e8-8a52-e28706ef47a5)

2024-10-02 00:22 UTC, tpdud406 commented
@tpdud406 

- 와아.. 위에 캡처해서 올린 내용을 푸시하지 않고..... 머지해버렸네요...
- 빨리 처리하겠습니다!!!